---
- name: include redhat variables
  include_vars: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: include debian variables
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

- name: Install ntp packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - ntp
    - ntpdate

#- name: include configuration part
#  include: configuration.yml

- name: configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp

- name: start and enable ntp service
  service:
    name: '{{ ntp_service }}'
    state: started
    enabled: yes
